
services:
  db:
    build: ./db 
    volumes:
      - ./pdb/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]

  frontend:
    build: ./frontend
    ports:
      - "2300:80"

  backend:
    build: ./backend
    ports:
      - "2345:2345"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  


    


    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info

  #   # command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - db
  dozer: 
    container_name: mydozer
    build: ./dozer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "2000:8080"
      - "50051:50051"
    tty: true


