
version: 1

app_name: GrowthGenie2
home_dir: ./.dozer4
cache_dir: ./.dozer4/cache
   
connections:
  - config: !Postgres
      user: postgres
      password: pgpass
      host: srv-captain--pgdb
      port: 5432
      database: postgres
      sslmode: disable
    name: pgcon
   

sources:
  - name: mutual_funds
    table_name: mutual_funds
    connection: pgcon
  - name: investment_accounts 
    table_name: investment_accounts
    connection: pgcon
  - name: transactions 
    table_name: transactions
    connection: pgcon
  - name: accounts 
    table_name: accounts
    connection: pgcon
  - name: mfDaily 
    table_name: accounts
    connection: pgcon
  


sql: |

  select *  into MFDailyPriceTable from mfdailyprice
  
    
endpoints: 
  - name: mf
    path: /mfdaily
    table_name: MFDailyPriceTable


 

