
version: 1

app_name: GrowthGenie2
home_dir: ./.dozer4
cache_dir: ./.dozer4/cache


   
connections:
  - config: !Postgres
      user: postgres
      password: pgpass
      host: 68.183.85.136
      port: 5689
      database: postgres
      schema: public
      sslmode: disable
    name: pgcon2

sources:
  - name: transactions 
    table_name: transactions
    connection:  pgcon2
  - name: stocks 
    table_name: stocks
    connection:  pgcon2
  - name: stocks_daily_price 
    table_name: stocks_daily_price
    connection:  pgcon2
  
   






  
    
endpoints: 

  - name: recent_transactions
    path: /recent_transactions
    table_name: transactions
    index:
      secondary:
        create:
          - !SortedInverted
              fields:
                - customer_id
                - date 




