
version: 1

app_name: GrowthGenie2
home_dir: ./.dozer4
cache_dir: ./.dozer4/cache
   
connections:
  - config: !Postgres
      user: postgres
      password: pgpass
      host: srv-captain--pgdb
      port: 5432
      database: postgres
      schema: public
      sslmode: disable
    name: pgcon2
   

sources:
  - name: mfdata 
    table_name: mfdata
    connection:  pgcon2
  



  
    
endpoints: 
  - name: mf
    path: /mfdaily
    table_name: mfdata


 

