
version: 1

app_name: GrowthGenie2
home_dir: ./.dozer4
cache_dir: ./.dozer4/cache
   
connections:
  - config: !Postgres
      user: postgres
      password: pgpass
      host: srv-captain--pgdb
      port: 5432
      database: postgres
      sslmode: disable
    name: pgcon
   

sources:
  - name: mfDaily 
    table_name: mfdata
    connection: pgcon
  


sql: |

  select *  into MFDailyPriceTable from mfdata
  
    
endpoints: 
  - name: mf
    path: /mfdaily
    table_name: MFDailyPriceTable


 

